# Generated by Django 5.1.7 on 2025-04-06 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_app', '0003_alter_currentreadings_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentreadings',
            name='date',
        ),
        migrations.RemoveField(
            model_name='currentreadings',
            name='time',
        ),
        migrations.AddField(
            model_name='currentreadings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
