# Generated by Django 5.1.7 on 2025-04-06 06:26

import meter_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_app', '0004_remove_currentreadings_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentreadings',
            name='timestamp',
            field=models.BigIntegerField(default=meter_app.models.get_timestamp_millis),
        ),
    ]
