# Generated by Django 5.1.7 on 2025-04-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_app', '0006_hourlyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('usage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
