# Generated by Django 5.1.7 on 2025-04-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_app', '0007_dailyusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusage',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
